#!/bin/bash -ue

: ${MYSQL:=mysql}

usage() {
  cat >&1 <<EOF
NAME
      generate-gallery - Create a static gallery web site with images based on NextCloud tag identifier.
SYNOPSIS
      generate-gallery [OPTIONS] DBNAME PREFIX-PATH TAG-ID OUTPUT-PATH

DESCRIPTION
      Exports tagged images from next cloud database DBNAME and creates a static gallery view at OUTPUT-PATH.

      Use must provide:
        DBNAME - database name for nextcloud. Only MySQL without authorization is supported right now.
        PREFIX-PATH - location of nextcloud files. For example: "/var/www/nextcloud/data/username".
        TAG-ID - images of which tag will be exported.
        OUTPUT-PATH - directory at which static website is generated.

      In generated website 3 main folders are created:
        - thumbnails contains small thumbnails visible on the main stream view;
        - view contains  medium size images when a user clicks on a thumbnail;
        - original contains either original images OR nothing (it is controled with --originals flag).

OPTIONS
      -h, --help
            print this help.
      --force
            delete OUTPUT-PATH before generation starts.
      --originals
            Allow originals to be downloaded. By default only view-thumbnails are for download.
      --limit <NUM>
            Limit number of converted images to NUM.

IMPROVEMENTS
      - Escaping of MySQL querries,...
      - Support of user/password for MySQL.
      - Support all next cloud DB engines.
      - Support more customizations (image sizes, copy original or not,....).
      - Integrate with next cloud gallery app.
      - Migrate from bash to safer tool
EOF
}

is_pos_num() {
  test "$1" -eq "$1" -a "$1" -gt "0" 2>/dev/null
}

FORCE=false
DOWNLOAD_ORIGINALS=false
LIMIT_QUERRY=
while [[ $# -gt 0 ]]; do
  i="$1"
  case $i in
      -h|--help)
      usage
      exit 0
    ;;
    --force)
      FORCE=true
      shift
    ;;
    --originals)
      DOWNLOAD_ORIGINALS=true
      shift
    ;;
    --limit)
      LIMIT="$2"
      if ! is_pos_num "$LIMIT"; then
        echo "limit NUM must be a positive integer" >&2
        exit 1
      fi
      shift 2
      LIMIT_QUERRY="LIMIT $LIMIT"
    ;;
    -*)
      echo "invalid option '$i'" >&2
      exit 1
    ;;
    *)
      break
    ;;
  esac
done

if [ "$#" -lt 4 ]; then
  echo "Not enough options"
  exit 1
fi

DB=$1
PREFIX_PATH=$2
TAG=$3
BUILD=$4

if [ ! -d "$PREFIX_PATH" ]; then
  echo "$PREFIX_PATH is not a valid prefix directory"
  exit 1
fi

if ! is_pos_num "$TAG"; then
  echo "$TAG is not a positive number"
  exit 1
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
SRC=$SCRIPT_DIR/src

if [ -e "$BUILD" -a "$FORCE" = "false" ]; then
  echo "Output directory already exist. Use option --force to remove it before generation" >&2
  exit 1
fi

# Create temporary directories for photos
TMP_DIR=$(mktemp -d)
SWAP_DIR=$(mktemp -d)

function finish {
  echo "Clean up of tmp dirs"
  rm -rf "$TMP_DIR" "$SWAP_DIR"
}
trap finish EXIT

# Work in TMP dir before replacing/creating output dir
chmod 0755 "$TMP_DIR"
THUMBNAIL_DIR=$TMP_DIR/thumbnails
VIEW_DIR=$TMP_DIR/view
ORIGINAL_DIR=$TMP_DIR/original
mkdir -p "$THUMBNAIL_DIR"
mkdir -p "$VIEW_DIR"
mkdir -p "$ORIGINAL_DIR"

# TODO: order by something more meaningful
FROM_WHERE="FROM oc_systemtag_object_mapping WHERE systemtagid=$TAG"
ORDER_BY="ORDER BY objectid"
COUNT_SELECT="SELECT COUNT(*) FROM (SELECT * FROM oc_systemtag_object_mapping WHERE systemtagid=$TAG $LIMIT_QUERRY) as qqqqq";
COLUMNS="objectid, systemtagid, ROW_NUMBER() OVER () AS ind, ($COUNT_SELECT) AS total"
$MYSQL -e "SELECT $COLUMNS $FROM_WHERE $ORDER_BY $LIMIT_QUERRY" "$DB" | while IFS=$'\t' read objectid systemtagid ind total; do
  if [ "$objectid" == objectid ]; then continue; fi
  echo -ne "\rProcessing image $ind out of $total... "

  $MYSQL -e "SELECT path, storage FROM oc_filecache WHERE fileid=$objectid" "$DB" | while IFS=$'\t' read path storage; do
    if [ "$path" == "path" ]; then continue; fi
    original="$PREFIX_PATH/$path"

    if [ ! -f "$original" ]; then
      echo "Path $original does not exist. Check your prefix." >&2
      exit 1;
    fi

    md5=$(md5sum "$original" | awk '{print $1}')
    extension="${original##*.}"
    thumbnail="$THUMBNAIL_DIR/$md5.$extension"
    new_file_name=$(basename "$thumbnail")

    convert -resize 750x750\>  "$original" "$thumbnail"
    touch "$thumbnail" -r "$original"
    chmod 0644 "$thumbnail"

    view_file=$VIEW_DIR/$new_file_name
    convert -resize 1500x1500\>  "$original" "$view_file"
    touch "$view_file" -r "$original"
    chmod 0644 "$view_file"

    if [ "$DOWNLOAD_ORIGINALS" == "true" ]; then
      # TODO: Consider soft link instead of copy
      new_original=$ORIGINAL_DIR/$new_file_name
      cp "$original" "$new_original"
      touch "$new_original" -r "$original"
      chmod 0644 "$new_original"
    fi

  done
done

# Print an empty line to output more text from a new line
echo

# Copy static files
cp -r "$SRC/static" "$TMP_DIR"
cp "$SRC/index-before.html" "$TMP_DIR/index.html"

# ADD HREFS
for i in "$THUMBNAIL_DIR"/*; do
  fname=$(basename "$i")
  thumbnail="thumbnails/$fname"
  view="view/$fname"
  original=$view
  if [ "$DOWNLOAD_ORIGINALS" == "true" ]; then
    original="original/$fname"
  fi
  echo "<a href=\"$view\" data-ngthumb=\"$thumbnail\" data-ngdownloadurl=\"$original\" ></a>" >>"$TMP_DIR/index.html"
done

# Finalize some files
cat "$SRC/index-after.html" >>"$TMP_DIR/index.html"

# Swap tmp dir with target dir
if [ -e "$BUILD" ]; then
  echo "Moving original build to tmp $SWAP_DIR"
  mv "$BUILD" "$SWAP_DIR"
fi

echo "Finalizing $BUILD dir"
mv "$TMP_DIR" "$BUILD"
